# Generated by Django 4.0.4 on 2022-06-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Post',
            new_name='title',
        ),
    ]
